controle_estoque/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('estoque.urls')),
]

estoque/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = 'estoque'
urlpatterns = [
    path('', views.PaginaPrincipal, name='PaginaPrincipal'),
    path('modificarproduto/<int:id_produto>', views.ModificarProduto, name='ModificarProduto'),
    path('deletarproduto/<int:id_produto>', views.DeletarProduto, name='DeletarProduto'),
    path('adicionarprodutos/', views.AdicionarProduto, name='AdicionarProdutos'),
    path('exibirprodutos/', views.ExibirProdutos, name="ExibirProdutos"),
    path('exibirprodutos/<int:id_produto>', views.DetalheProdutos, name="Detalhes"),
]

estoque/models.py
from django.db import models

class Produto(models.Model):
    nome = models.CharField('Nome',max_length=100)
    quantidade = models.PositiveIntegerField('Quantidade',default=0)
    valor = models.DecimalField('Valor',default=0, max_digits=10, decimal_places=2)

    def __str__(self):
        return self.nome

estoque/forms.py
from django import forms
from .models import Produto

class FormProdutos(forms.ModelForm):

    class Meta:
        model = Produto
        fields =['nome', 'quantidade', 'valor']

estoque/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Produto
from .forms import FormProdutos



def PaginaPrincipal(request):
    return render(request, 'estoque/paginaprincipal.html')

def ExibirProdutos(request):
    produtos = Produto.objects.all()
    context = {
        'produtos': produtos,
    }

    try:
        nome_pesquisado = request.POST['nome']

        if nome_pesquisado:
            prodpesquisa = Produto.objects.get(nome = nome_pesquisado)
            return redirect(reverse('estoque:Detalhes', args=(prodpesquisa.id,)))


    except(KeyError):
        return render(request, 'estoque/exibirprodutos.html', context)
    except(Produto.DoesNotExist):
        context['erro'] = "Não existe nenhum produto com este nome."
        return render(request, 'estoque/exibirprodutos.html', context)

    else:
        return HttpResponseRedirect(reverse('estoque:ExibirProdutos'))

def DetalheProdutos(request, id_produto):
    produto = Produto.objects.get(pk=id_produto)
    context ={
        'produto': produto,
    }
    return render(request, 'estoque/detalhes.html', context)

def AdicionarProduto(request):
    form = FormProdutos(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('estoque:ExibirProdutos')

    return render(request, 'estoque/adicionarproduto.html', {'form': form})

def ModificarProduto(request, id_produto):
    produto = Produto.objects.get(pk=id_produto)
    form = FormProdutos(request.POST or None, instance=produto)

    if form.is_valid():
        form.save()
        return redirect('estoque:ExibirProdutos')

    context={
        'form': form
    }
    return render(request, 'estoque/modificarproduto.html', context)

def DeletarProduto(request, id_produto):
    prod = Produto.objects.get(pk=id_produto)
    prod.delete()
    return redirect('estoque:ExibirProdutos')

estoque/templates/estoque/adicionarproduto.html
{% extends 'estoque/base.html' %}
{% block title %}Adicionar Produtos{% endblock %}
{% block content %}
<div class="container text-center">
    <div class="row">
        <div class="col-xl-12 mx-auto">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Adicionar</button>
                <input type="button" value="Cancelar" class="btn btn-secondary" onclick="location.href = '{% url 'estoque:PaginaPrincipal'%}'"/>
            </form>
        </div>
    </div>
</div>
{% endblock %}

estoque/templates/estoque/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'estoque/css/bootstrap.css' %}" >

    <script src="{% static 'estoque/jquery-3.3.1.slim.min.js' %}" ></script>
    <script src="{% static 'estoque/popper.min.js' %}" ></script>
    <script src="{% static 'estoque/js/bootstrap.min.js' %}" ></script>
</head>

    <!-- Custom fonts for this template -->
    <link href="{% static 'estoque/theme/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'estoque/theme/vendor/simple-line-icons/css/simple-line-icons.css' %} " rel="stylesheet" type="text/css">


    <!-- Custom styles for this template -->
    <link href="{% static 'estoque/theme/css/landing-page.css' %}" rel="stylesheet">

    <title>{% block title %}{% endblock %}</title>

<body>

    <!-- Navigation -->
  <nav class="navbar navbar-light bg-light static-top">
    <div class="container">
    <div class="col-md-8">
      <a class="navbar-brand" href="{% url 'estoque:PaginaPrincipal' %}">Controle de Estoque</a>
    </div>
      <a class="btn btn-primary" href="{% url 'estoque:ExibirProdutos' %}">Exibir Produtos</a>
      <a class="btn btn-primary" href="{% url 'estoque:AdicionarProdutos' %}">Adicionar Produtos</a>
    </div>
  </nav>


        {% block content %}
        {% endblock %}


  <!-- Footer -->
  <footer class="footer bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
          <ul class="list-inline mb-2">
            <li class="list-inline-item">
              <a href="#">Sobre</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Contatos</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Termos de Uso</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Política de Privacidade</a>
            </li>
          </ul>
          <p class="text-muted small mb-4 mb-lg-0">&copy; Richard Lucas 2019. Todos os direitos reservados.</p>
        </div>
        <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
          <ul class="list-inline mb-0">
            <li class="list-inline-item mr-3">
              <a href="#">
                <i class="fab fa-facebook fa-2x fa-fw"></i>
              </a>
            </li>
            <li class="list-inline-item mr-3">
              <a href="#">
                <i class="fab fa-twitter-square fa-2x fa-fw"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-instagram fa-2x fa-fw"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

    </body>
</html>

estoque/templates/estoque/detalhes.html
{% extends 'estoque/base.html' %}
{% block title %}Detalhes do Produto{% endblock %}
{% block content %}
<div class="container text-center">
    <div class="row">
        <div class="col-xl-12 mx-auto">
            <p>Nome do produto: {{ produto.nome }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-12 mx-auto">
            <p>Preço do produto: {{ produto.valor }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-12 mx-auto">
            <p>Produtos em estoque: {{ produto.quantidade }}</p>
        </div>
    </div>

    <input type="button" value="Modificar" class="btn btn-primary" onclick="location.href = '{% url 'estoque:ModificarProduto' produto.pk %}'"/>
    <input type="button" value="Deletar" class="btn btn-danger" onclick="location.href = '{% url 'estoque:DeletarProduto' produto.pk %}'"/>
    <input type="button" value="Voltar" class="btn btn-secondary" onclick="location.href = '{% url 'estoque:ExibirProdutos'%}'"/>

</div>

{% endblock %}

estoque/templates/estoque/exibirprodutos.html
{% extends 'estoque/base.html' %}
{% block title %}Lista de Produtos{% endblock %}
{% block content %}
<header>
<div class="overlay">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <h1 class="text-center font-weight-bold mb-5">Lista de Produtos</h1>
            </div>
        </div>
    </div>
</div>
</header>

<div class="container">
    <div class="row">
        <div class="col-xl-12 mx-auto">
        <form method="POST">
            {% csrf_token %}
            <div class="form-inline">
                <div class="col-md">
                <label>Nome do produto: </label>
                </div>
                <div class="col-md">
                <input type="text" class="form-control" name="nome" placeholder="Produto">
                </div>
                <div class="col-md">
                <input type="submit" class="btn btn-secondary" value="Pesquisar">
                </div>
            </div>
        </form>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Pesquisa completa!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <p>Este produto não existe.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

{% if erro %}
    <script>
    $(document).ready(function(){
    $("#myModal").modal();
  });
    </script>
{% endif %}


<section class="text-center">
    <div class="container">
        <div class="row">
                <div class="list-group">
                    {% for prods in produtos.all %}
                    <a href="{% url 'estoque:Detalhes' prods.pk %}" class="list-group-item list-group-item-action">{{ prods.nome }}</a>
                    {% endfor %}
                </div>
        </div>
    </div>

<input type="button" class="btn btn-primary" value="Voltar" onclick="location.href='{% url 'estoque:PaginaPrincipal' %}'"/>
</section>

{% endblock %}

estoque/templates/estoque/modificarproduto.html
{% extends 'estoque/base.html' %}
{% block title %}Modificar produtos{% endblock %}
{% block content %}

<div class="container text-center">
    <div class="row">
        <div class="col-xl-12 mx-auto">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Modificar</button>
                <input type="button" value="Cancelar" class="btn btn-secondary" onclick="location.href = '{% url 'estoque:ExibirProdutos'%}'"/>
            </form>
        </div>
    </div>
</div>

{% endblock %}

estoque/templates/estoque/paginaprincipal.html
{% extends 'estoque/base.html' %}

{% block title %}Controle de Estoque{% endblock %}

{% block content %}
<header class="masthead text-white text-center">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <h1 class="mb-5">Controle de Estoque</h1>
        </div>
      </div>
    </div>
</header>

<!-- Icons Grid -->
  <section class="features-icons bg-light text-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="icon-screen-desktop m-auto text-primary" onclick="location.href='{% url 'estoque:ExibirProdutos' %}'"></i>
            </div>
            <h3>Exibir os produtos</h3>
            <p class="lead mb-0">Exibir uma lista com os produtos registrados no estoque</p>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="features-icons-item mx-auto mb-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="icon-check m-auto text-primary" onclick="location.href='{% url 'estoque:AdicionarProdutos' %}'"></i>
            </div>
            <h3>Adicionar novo produto</h3>
            <p class="lead mb-0">Adicionar novos produtos no estoque</p>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}